# Generated by Django 4.2 on 2024-01-20 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("booking_start_date", models.DateField()),
                ("booking_end_date", models.DateField()),
                ("length_of_stay", models.IntegerField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("guests", models.IntegerField()),
                (
                    "cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6),
                ),
                ("paid", models.BooleanField(blank=True, default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
